# Generated by Django 3.0.2 on 2020-08-08 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FPO',
            fields=[
                ('fid', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('statename', models.CharField(default='', max_length=200)),
                ('district', models.CharField(default='', max_length=200)),
                ('programme', models.CharField(default='', max_length=200)),
                ('resource', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('legalformfpo', models.CharField(default='', max_length=200)),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='', max_length=300)),
                ('contact', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='fpoproduct',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(default='', max_length=200)),
                ('fponame', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('timeline', models.DateField(default=datetime.date.today)),
                ('quantity', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.FPO')),
            ],
        ),
    ]
